version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Webhook Server
          command: |
            node server.js
      - run:
          name: Deploy to EC2
          command: |
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST 'echo "Connected to EC2"'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
